apiVersion: v1
kind: ReplicationController
metadata:
    name: busybox-rc
    namespace: default
    labels:
      name: busybox-rc
      app: busybox
spec:
  replicas: 1
  selector:
    app: busybox
  template:
    metadata:
      name: busybox-pod
      labels:
        name: busybox-pod
        app: busybox
    spec:
      containers:
      - image: busybox
        command:
          - sleep
          - "3600"
        imagePullPolicy: IfNotPresent
        name: busybox
