apiVersion: v1
kind: Service
metadata:
  name: busybox-svc
  namespace: default
  labels:
    name: busybox-svc
    app: busybox
spec:
  type: NodePort
  ports:
  - port: 22
    protocol: TCP
  selector:
    app: busybox
