apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-svc
spec:
  # Uncomment next line if you want to expose redis to the wilds of the internet -- also useful for accessing this service as a cloud of remote mercenaries from your lappy
  # type: NodePort
  type: LoadBalancer
  # get the actual exposed port from  That port will be reported in your Service's spec.ports[*].nodePort field.
  ports:
    # the port that this service should serve on
  - port: 6379
    nodePort: 30379
    targetPort: 6379
  selector:
    name: redis-rc
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-rc
  labels:
    name: redis-rc
spec:
  replicas: 1
  selector:
    name: redis-rc
  template:
    metadata:
      labels:
        name: redis-rc
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
